name 'oracle-weblogic'
maintainer 'Shinya Yanagihara'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures oracle-weblogic'
long_description 'Installs/Configures oracle-weblogic'
version '0.1.0'
