name 'oracle-inventory'
maintainer 'Shinya Yanagihara'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures oracle-inventory'
long_description 'Installs/Configures oracle-inventory'
version '0.1.0'
